In [ ]:
# LogReg
# KNN
# Decision Tree
# Random Forest
# SVM

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [3]:
df.shape

(768, 9)

In [5]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [6]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [7]:
df['Outcome'].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [8]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]  # Outcome
print(type(x))
print(type(y))
print(x.shape)
print(y.shape)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
(768, 8)
(768,)


In [9]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(576, 8)
(192, 8)
(576,)
(192,)


In [12]:
x_train.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
173            1       79             60             42       48  43.5   
695            7      142             90             24      480  30.4   
210            2       81             60             22        0  27.7   
2              8      183             64              0        0  23.3   
418            1       83             68              0        0  18.2   

     DiabetesPedigreeFunction  Age  
173                     0.678   23  
695                     0.128   43  
210                     0.290   25  
2                       0.672   32  
418                     0.624   27

In [13]:
y_train.head()

173    0
695    1
210    0
2      1
418    0
Name: Outcome, dtype: int64

#### Applying KNN Classifier

In [14]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,classification_report

In [25]:
m1 = KNeighborsClassifier(n_neighbors=19)
m1.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=19)

In [26]:
# Accuracy
print('Training Score',m1.score(x_train,y_train))
print('Testing Score',m1.score(x_test,y_test))

Training Score 0.7708333333333334
Testing Score 0.78125


In [27]:
ypred_m1 = m1.predict(x_test)
print(ypred_m1)

[0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 1 1 0 0 1 0 1 1 0 0 1 1
 0 0 0 1 0 0 1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 1 0 0
 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0
 0 0 0 1 0 1 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 0 1 1 0 1 0 0 1 0 0 0 0 0 0
 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 1 1 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0
 0 0 1 0 1 1 0]


In [28]:
cm_m1 = confusion_matrix(y_test,ypred_m1)
print(cm_m1)
print(classification_report(y_test,ypred_m1))

[[112  20]
 [ 22  38]]
              precision    recall  f1-score   support

           0       0.84      0.85      0.84       132
           1       0.66      0.63      0.64        60

    accuracy                           0.78       192
   macro avg       0.75      0.74      0.74       192
weighted avg       0.78      0.78      0.78       192



#### 1) Find the percentage of misclassification? 

In [29]:
per = (20+22)/(112+20+22+38)
print(per*100)

21.875


#### Applying Decision Tree Classifier

In [30]:
from sklearn.tree import DecisionTreeClassifier

In [40]:
m2 = DecisionTreeClassifier(criterion='gini',max_depth=8)
m2.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=8)

In [41]:
# Accuracy
print('Training Score',m2.score(x_train,y_train))
print('Testing Score',m2.score(x_test,y_test))
# Overffited model

Training Score 0.9548611111111112
Testing Score 0.7708333333333334


In [42]:
ypred_m2 = m2.predict(x_test)
print(ypred_m2)

[0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 1 0 1 1 0 1 1 1
 1 1 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 1 1 0 1
 0 0 0 0 1 0 0 0 1 1 1 1 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 1 0 0
 0 0 1 1 0 1 1 1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 0 0 0 0 0 0
 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 1 1 1 1 1 1 0 0 0 0 0 0
 0 0 0 0 0 1 0]


In [43]:
cm_m2 = confusion_matrix(y_test,ypred_m2)
print(cm_m2)
print(classification_report(y_test,ypred_m2))

[[109  23]
 [ 21  39]]
              precision    recall  f1-score   support

           0       0.84      0.83      0.83       132
           1       0.63      0.65      0.64        60

    accuracy                           0.77       192
   macro avg       0.73      0.74      0.74       192
weighted avg       0.77      0.77      0.77       192



#### Applying Random Forest Classifier

In [44]:
from sklearn.ensemble import RandomForestClassifier

In [68]:
m3 = RandomForestClassifier(n_estimators=85,criterion='gini',max_depth=7)
m3.fit(x_train,y_train)

RandomForestClassifier(max_depth=7, n_estimators=85)

In [69]:
print('Training score',m3.score(x_train,y_train))
print('Testing score',m3.score(x_test,y_test))
# Overfiited model

Training score 0.9427083333333334
Testing score 0.7916666666666666


In [70]:
ypred_m3 = m3.predict(x_test)
print(ypred_m3)

[0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 1 1 1 0 0 1 0 1 1 0 1 1 0
 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 1 0 0 0
 0 0 0 0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 1 0 0
 0 0 0 1 0 1 1 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 1 0 1 1 0 1 0 0 1 1 0 0 0 0 0
 0 1 0 0 0 1 1 0 0 0 0 0 1 0 1 1 0 1 1 0 0 1 1 0 0 1 1 1 0 1 1 0 0 0 0 1 0
 0 0 0 0 1 1 0]


In [71]:
cm_m3 = confusion_matrix(y_test,ypred_m3)
print(cm_m3)
print(classification_report(y_test,ypred_m3))

[[110  22]
 [ 18  42]]
              precision    recall  f1-score   support

           0       0.86      0.83      0.85       132
           1       0.66      0.70      0.68        60

    accuracy                           0.79       192
   macro avg       0.76      0.77      0.76       192
weighted avg       0.80      0.79      0.79       192



#### Applying SVM Classifier

In [72]:
from sklearn.svm import SVC

In [77]:
m4 = SVC(kernel='linear',C=1)
m4.fit(x_train,y_train)

SVC(C=1, kernel='linear')

In [78]:
print('Training Score',m4.score(x_train,y_train))
print('Testing Score',m4.score(x_test,y_test))

Training Score 0.78125
Testing Score 0.7916666666666666


In [79]:
ypred_m4 = m4.predict(x_test)
print(ypred_m4)

[0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 1 1 0 0 1 0 1 1 0 0 1 1
 0 0 0 1 0 0 1 1 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 1 0 0 0
 0 0 1 0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0
 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 1 1 0 1 0 0 1 1 0 0 0 0 0
 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 0 1 1 0 0 1 1 1 0 0 0 0 0 0 0 1 0
 0 1 0 0 1 1 0]


In [80]:
cm_m4 = confusion_matrix(y_test,ypred_m4)
print(cm_m4)
print(classification_report(y_test,ypred_m4))

[[114  18]
 [ 22  38]]
              precision    recall  f1-score   support

           0       0.84      0.86      0.85       132
           1       0.68      0.63      0.66        60

    accuracy                           0.79       192
   macro avg       0.76      0.75      0.75       192
weighted avg       0.79      0.79      0.79       192



#### Applying Logistic Regression

In [82]:
from sklearn.linear_model import LogisticRegression

In [85]:
m5 = LogisticRegression(solver='liblinear')
m5.fit(x_train,y_train)

LogisticRegression(solver='liblinear')

In [86]:
print('Training Score',m5.score(x_train,y_train))
print('Testing Score',m5.score(x_test,y_test))

Training Score 0.7760416666666666
Testing Score 0.7708333333333334


In [87]:
ypred_m5 = m5.predict(x_test)
print(ypred_m5)

[0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 1 0 1 1 0 0 1 1
 0 0 0 1 0 0 1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0
 0 0 0 1 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 1 0 1 1 0 1 0 0 1 1 0 0 0 0 0
 1 1 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 0 1 1 0 0 1 1 1 0 0 0 0 0 0 0 1 0
 0 0 1 0 1 1 0]


In [88]:
cm_m5 = confusion_matrix(y_test,ypred_m5)
print(cm_m5)
print(classification_report(y_test,ypred_m5))

[[114  18]
 [ 26  34]]
              precision    recall  f1-score   support

           0       0.81      0.86      0.84       132
           1       0.65      0.57      0.61        60

    accuracy                           0.77       192
   macro avg       0.73      0.72      0.72       192
weighted avg       0.76      0.77      0.77       192



#### Q) Write a function whose parameters are - model, x_train,x_test,y_train,y_test. The function should return training and testing score, predicted values, confusion matrix and classifrication report


In [89]:
def apply_model(model, x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    ypred = model.predict(x_test)
    cm = confusion_matrix(y_test,ypred)
    print('Training Score',model.score(x_train,y_train))
    print('Testing Score',model.score(x_test,y_test))
    print('Predicted Values\n',ypred)
    print('Confusion_Matrix\n',cm)
    print('Classification_Report\n',classification_report(y_test,ypred))

In [90]:
# 1) RanodmForest
w1 = RandomForestClassifier(n_estimators=80,criterion='entropy',max_depth=8,min_samples_split=15)
apply_model(w1,x_train,x_test,y_train,y_test)

Training Score 0.8940972222222222
Testing Score 0.78125
Predicted Values
 [0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 1 1 1 0 0 1 0 1 1 0 1 1 0
 0 0 0 1 0 0 1 1 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 1 0 1 0 0 0
 0 0 1 0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 1 0 1 0 0
 0 0 0 1 0 1 1 0 0 0 0 0 1 1 1 1 0 0 1 0 0 0 1 0 1 1 0 1 0 1 1 1 0 0 0 0 0
 0 1 0 0 0 1 1 0 0 0 0 0 1 0 1 1 0 1 1 0 0 1 1 0 0 1 1 1 0 1 1 0 0 0 0 1 0
 0 0 0 0 1 1 0]
Confusion_Matrix
 [[107  25]
 [ 17  43]]
Classification_Report
               precision    recall  f1-score   support

           0       0.86      0.81      0.84       132
           1       0.63      0.72      0.67        60

    accuracy                           0.78       192
   macro avg       0.75      0.76      0.75       192
weighted avg       0.79      0.78      0.78       192



In [92]:
# 2) SVM
w2 = SVC(kernel='linear',C=0.01)
apply_model(w2,x_train,x_test,y_train,y_test)

Training Score 0.7638888888888888
Testing Score 0.7864583333333334
Predicted Values
 [0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 1 1 0 0 1 0 1 1 0 0 1 1
 0 0 0 1 0 0 1 1 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 1 0 0 0
 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0
 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 1 0 1 1 0 1 0 0 1 1 0 0 0 0 0
 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 0 1 1 0 0 1 1 1 0 0 0 0 0 0 0 1 0
 0 0 0 0 1 1 0]
Confusion_Matrix
 [[114  18]
 [ 23  37]]
Classification_Report
               precision    recall  f1-score   support

           0       0.83      0.86      0.85       132
           1       0.67      0.62      0.64        60

    accuracy                           0.79       192
   macro avg       0.75      0.74      0.75       192
weighted avg       0.78      0.79      0.78       192



In [94]:
# 3) Decision Tree
w3 = DecisionTreeClassifier(criterion='entropy',max_depth=9)
apply_model(w3,x_train,x_test,y_train,y_test)

Training Score 0.9618055555555556
Testing Score 0.7239583333333334
Predicted Values
 [0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 1 0 1 1 0 1 1 1
 1 1 0 1 0 0 0 1 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 1
 0 0 1 0 1 0 0 0 1 1 1 1 0 1 0 0 1 0 0 1 0 1 1 0 1 0 0 0 0 1 0 0 0 0 1 0 0
 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 1 1 0 1 0 0 1 1 0 0 0 0 0
 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 1 1 1 1 1 0 0 0 0 0 0
 0 0 0 0 0 1 0]
Confusion_Matrix
 [[103  29]
 [ 24  36]]
Classification_Report
               precision    recall  f1-score   support

           0       0.81      0.78      0.80       132
           1       0.55      0.60      0.58        60

    accuracy                           0.72       192
   macro avg       0.68      0.69      0.69       192
weighted avg       0.73      0.72      0.73       192



In [96]:
# 4) Log Reg
w4 = LogisticRegression(solver='liblinear')
apply_model(w4,x_train,x_test,y_train,y_test)

Training Score 0.7760416666666666
Testing Score 0.7708333333333334
Predicted Values
 [0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 1 0 1 1 0 0 1 1
 0 0 0 1 0 0 1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0
 0 0 0 1 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 1 0 1 1 0 1 0 0 1 1 0 0 0 0 0
 1 1 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 0 1 1 0 0 1 1 1 0 0 0 0 0 0 0 1 0
 0 0 1 0 1 1 0]
Confusion_Matrix
 [[114  18]
 [ 26  34]]
Classification_Report
               precision    recall  f1-score   support

           0       0.81      0.86      0.84       132
           1       0.65      0.57      0.61        60

    accuracy                           0.77       192
   macro avg       0.73      0.72      0.72       192
weighted avg       0.76      0.77      0.77       192



In [97]:
# 5) KNN
w5 = KNeighborsClassifier(n_neighbors=35)
apply_model(w5,x_train,x_test,y_train,y_test)

Training Score 0.7413194444444444
Testing Score 0.7864583333333334
Predicted Values
 [0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 1 1 0 0 1 0 1 1 0 0 1 1
 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0
 0 0 0 1 0 1 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 0 0 0 1 0 0 0 1 1 0
 0 0 0 0 1 1 0]
Confusion_Matrix
 [[118  14]
 [ 27  33]]
Classification_Report
               precision    recall  f1-score   support

           0       0.81      0.89      0.85       132
           1       0.70      0.55      0.62        60

    accuracy                           0.79       192
   macro avg       0.76      0.72      0.73       192
weighted avg       0.78      0.79      0.78       192

